site_name: OSG All-Hands Meetings
site_url: https://opensciencegrid.github.io/all-hands/
repo_url: null
theme:
  name: material

pages:
  - Overview: index.md
  - 2018:
    - Home: 2018/index.md

markdown_extensions:
  - admonition
  - toc(permalink=true)
