site_name: OSG All-Hands Meetings
site_url: https://opensciencegrid.github.io/all-hands/
repo_url: null
theme:
  name: material

pages:
  - Home: index.md
  - 2018:
    - General Info: 2018/index.md
    - Hotels: 2018/hotels.md

markdown_extensions:
  - admonition
  - toc(permalink=true)
