site_name: OSG All-Hands Meetings
site_url: https://opensciencegrid.org/all-hands/
repo_url: https://github.com/opensciencegrid/all-hands/
theme:
  name: material
  favicon: img/favicon.ico

nav:
  - Home: index.md
  - 2022:
    - General Info: 2022/index.md
  - 2021:
    - General Info: 2021/index.md
    - Schedule: 2021/schedule.md
    - Registration: 2021/registration.md
    - Meeting Logistics: 2021/technology.md
  - 2020:
    - General Info: 2020/index.md
    - Schedule: 2020/schedule.md
    - Registration: 2020/registration.md
    - Meeting Logistics: 2020/technology.md
  - 2019:
    - General Info: 2019/index.md
  - 2018:
    - General Info: 2018/index.md
    - Schedule: 2018/schedule.md
    - Cost & Registration: 2018/registration.md
    - Hotels: 2018/hotels.md
    - Local Details: 2018/local.md
    - On Your Own: 2018/on-your-own.md

markdown_extensions:
  - admonition
  - toc:
      permalink: True
