site_name: OSG All-Hands Meetings
site_url: https://opensciencegrid.github.io/all-hands/
repo_url: null
theme:
  name: material
  favicon: img/favicon.ico

pages:
  - Home: index.md
  - 2018:
    - General Info: 2018/index.md
    - Schedule: 2018/schedule.md
    - Cost & Registration: 2018/registration.md
    - Hotels: 2018/hotels.md
    - Local Details: 2018/local.md
    - On Your Own: 2018/on-your-own.md

markdown_extensions:
  - admonition
  - toc(permalink=true)
